### ISSUE TITLE
2.16.1: breaks WooCommerce (2.6.14) ?add-to-cart processing in some cases  

### ISSUE THREAD

**Issue by lkraav** [johnbillion/query-monitor#277] opened 2017-11-01 13:01 UTC
Hey. Just discovered that latest QM release is directly involved in breaking our store's checkout flow, for the first time ever. Disabling QM immediately helps.

The symptom is adding the product to the cart and going to checkout causes WC to display "Item that is no longer available has been removed from your cart" error and the cart remains empty.

I will do a quick bisect run here to find out what's happening and report back.

**Comment by lkraav** [comment] 2017-11-01 13:07
Bisect shows the bad commit to be 877b69ec0b64cca4a5e81456ea82854495c2bd8e

**Comment by johnbillion** [comment] 2017-11-01 13:16
Thanks for the report. The `Undefined variable: args` notice was fixed in a later commit, so that's a red herring.

* Can you see any other errors in your PHP error log?
* Does the `Capability Checks` panel in QM appear to be working as expected? (Anything look broken?)
* Are you able to deactivate any other plugins relating to user capabilities to see if they're impacting things?

**Comment by lkraav** [comment] 2017-11-01 13:21
No other errors. Isolated the problem to `register_qm_collector_caps()` thus far, so it's not the output layer.

This is a WooCommerce Memberships system, a plugin which does play heavily with caps.

**Comment by lkraav** [comment] 2017-11-01 13:28
The issue is caused by `$trace = new QM_Backtrace` call inside the `filter_user_has_cap`.

If I comment this block out and just let it `return $user_caps`, everything works again.

Any thoughts on this angle?

**Comment by johnbillion** [comment] 2017-11-01 13:44
Cheers.

`QM_Backtrace` is used in a bunch of places throughout QM (most stack traces you see are generated by `QM_Stacktrace`).

It could be that this sort of data collection for every user capability check simply uses too much memory, but memory exhaustion would show up in your PHP error logs.

Idea: Can you comment out these four lines and see if it makes a difference? https://github.com/johnbillion/query-monitor/blob/74700bd1c0eb05cb4382e2dfaf696444124808a2/classes/Backtrace.php#L56-L59

**Comment by johnbillion** [comment] 2017-11-14 16:11
I've recently done some work to greatly reduce the amount of memory that QM uses (around 70% in some cases). If you want to try it out and see if it fixes this issue, check out [the develop branch](https://github.com/johnbillion/query-monitor/tree/develop).

**Comment by lkraav** [comment] 2017-11-21 08:36
@johnbillion does 2.17.0 already include this memory reduction work?

**Comment by johnbillion** [comment] 2017-11-21 11:40
Not yet, no. It'll be in 2.18.0.

**Comment by johnbillion** [comment] 2018-01-31 00:09
Closing this as a duplicate of #288.

**Closed by johnbillion** 2018-01-31 00:09 UTC
Labels: awaiting feedback, priority:1
