### ISSUE TITLE
Feature request: export to csv/excel

### ISSUE THREAD

**Issue by wpsumo** [johnbillion/query-monitor#593] opened 2021-05-13 10:37 UTC
Suggest to add export to csv/excel file. Would be very useful to send over to plugin developers to show the table headline and queries that is an issue or could be improved. Export for each view.

**Comment by johnbillion** [comment] 2021-05-13 18:52
Related: #320

**Comment by johnbillion** [comment] 2022-09-09 00:28
Duplicate of #174 (close enough).

**Closed by johnbillion** 2022-09-09 00:28 UTC
Labels: type:feature request
