### ISSUE TITLE
Website crashes upon deactivating query-monitor

### ISSUE THREAD

**Issue by nygaardc** [johnbillion/query-monitor#580] opened 2021-04-06 10:19 UTC
Thanks for a great plugin. I'm testing the speed of all my plugins using google lighthouse.

Upon deactivating query-monitor to test the page speed without, my site crashes.

I get the following errors:

Warning: Trying to access array offset on value of type bool in /srv/users/liheinfo/apps/liheinfo/public/wp-
content/plugins/wordpress-seo/src/helpers/schema/image-helper.php on line 98

Warning: Trying to access array offset on value of type bool in /srv/users/liheinfo/apps/liheinfo/public/wp-
content/plugins/wordpress-seo/src/helpers/schema/image-helper.php on line 100

Warning: Trying to access array
offset on value of type bool in /srv/users/liheinfo/apps/liheinfo/public/wp-
content/plugins/wordpress-seo/src/helpers/schema/image-helper.php on line 101

When I activate the query monitor plugin again, the error diasppears.

How can I prevent these errors to stay if I deactivate the plugin?

Thanks a lot for your help.

**Comment by johnbillion** [comment] 2021-04-06 10:52
When Query Monitor is active, do the errors show up in the PHP Errors panel?

**Comment by nygaardc** [comment] 2021-04-06 11:51
Dear John,
The plugin reports no warnings or notices. Everything seems to be running smoothly.

**Comment by nygaardc** [comment] 2021-04-06 12:26
Dear John,
I just found that the plugin causing trouble is Yoast SEO. If I remove this plugin the issue disappears. So it's nothing to do with query-monitor. It was just when I removed query-monitor your plugin didn't any longer "cover" for the error in Yoast SEO.
Thanks for your great plugin and help.

**Comment by johnbillion** [comment] 2021-04-06 12:28
Yeah the problem is with Yoast SEO but Query Monitor should be alerting you to that warning. Let me look into it.

**Comment by nygaardc** [comment] 2021-04-06 12:30
I just deactivated Yoast, updated to the latest version, activated it, and now Query Monitor gives me the errors. But I guess they need to be fixed via Yoast SEO support.

**Comment by johnbillion** [comment] 2021-04-26 21:44
I've not been able to reproduce this problem so I'll close this off. If anyone else sees this problem please feel free to comment with more details.

**Closed by johnbillion** 2021-04-26 21:44 UTC
Labels: awaiting testing
