### ISSUE TITLE
The h1 tag in the header

### ISSUE THREAD

**Issue by KasapovDmitry** [johnbillion/query-monitor#752] opened 2023-03-22 14:43 UTC
Hi. We do SEO on the site. And we need one h1 header. The plugin makes us a second header h1&lt;h1 class="qm-title-heading"&gt;Query Monitor&lt;/h1&gt;. How can I remove or fix it?

**Comment by johnbillion** [comment] 2023-03-22 17:19
Duplicate of #725

**Closed** 2023-03-22 17:19 UTC
