### ISSUE TITLE
Feature request: Export results to text file or clipboard

### ISSUE THREAD

**Issue by bozzmedia** [johnbillion/query-monitor#320] opened 2018-03-16 00:03 UTC
Great plugin! It would be useful to easily export the results of QM for sharing with support staff and team members. At the moment I'm using screenshots which is not ideal. Thanks for the consideration!

**Comment by Mte90** [comment] 2018-03-17 11:59
There is already my old pr for that https://github.com/johnbillion/query-monitor/pull/178

**Comment by johnbillion** [comment] 2022-09-09 00:28
Duplicate of #174 (close enough).

**Closed by johnbillion** 2022-09-09 00:28 UTC
