### ISSUE TITLE
llegal offset type in isset or empty

### ISSUE THREAD

**Issue by kilianso** [johnbillion/query-monitor#643] opened 2022-01-07 09:37 UTC
Hey there! I'm receiving quite a bunch of errors and warning in query monitor but as it seems, they are all caused by the plugin itself. I'm using the Wordpress 5.8.3

`llegal offset type in isset or empty` and `Array to string conversion`. Are these known issues?

![Screenshot 2022-01-07 at 10 32 44](https://user-images.githubusercontent.com/15088651/148523553-a6949dcb-2564-4ac3-b830-a2396f08d9f6.png)

**Comment by johnbillion** [comment] 2022-01-07 11:27
Thanks for the report. I'll take a look.

**Comment by johnbillion** [comment] 2022-01-07 20:37
Do you have any errors or strange output on the `Scripts` or `Styles` panels in QM? The error that you're seeing is being caused by a script or style on your site that's either using a handle name that is not a string, or declares a dependency with a handle name that's not a string.

I could would around this error in QM but it would paper over the real problem.

If you could check and let me know that would be great.

**Comment by kilianso** [comment] 2022-01-10 18:34
Hey @johnbillion
Thanks for pointing that out. Seems like it is related to some `admin-editor-styles`. It's kinda hard to find the root of the issue but it's not caused by this plugin.

<img width="1512" alt="Screenshot 2022-01-10 at 19 30 48" src="https://user-images.githubusercontent.com/15088651/148819592-321a1b34-6c2f-4a9a-b629-71009a946ff2.png">

**Comment by johnbillion** [comment] 2022-01-27 11:07
Thanks for confirming. I'll close this off in that case because these PHP warnings are valid in this situation. Hope you can find the problem!

**Closed by johnbillion** 2022-01-27 11:07 UTC
Labels: awaiting feedback
