### ISSUE TITLE
Check if project is not using jQuery to include it from Google CDN (for example)

### ISSUE THREAD

**Issue by NedkoHristov** [johnbillion/query-monitor#324] opened 2018-04-12 08:07 UTC
I just tried the new version and I got this message:
"A JavaScript problem on the page is preventing Query Monitor from working correctly. jQuery may have been blocked from loading."
It's probably issue from my configuration, but if the query-monitor requires a jQuery it would be a good idea to add a check and if there's none to include from some CDN (for example - https://developers.google.com/speed/libraries/). This will prevent such errors in future use.

Btw great design. Good work, everybody!

**Comment by johnbillion** [comment] 2018-04-12 08:59
Thanks for the report. Is there something (eg. a plugin or theme) on your site that is affecting the way that jQuery loads?

**Comment by NedkoHristov** [comment] 2018-04-12 09:04
Probably some "optimizations" that I do 😆 query-monitor does not relates with this issue.
If there's a better place to log this improvement proposition I'll be happy to help.

**Comment by johnbillion** [comment] 2018-04-12 09:11
Any errors in the `Scripts` panel in QM?

**Comment by NedkoHristov** [comment] 2018-04-12 10:59
Everything looks normal.
Btw it would be great if on error or warning query-monitor colors the rows and/or have some sorting filter in order to find faster if there's anything interesting.

**Comment by johnbillion** [comment] 2018-04-12 11:16
The Scripts and Styles panels will show a bright red warning if there is a problem with the dependencies system.

Without taking a look at your site I'm not sure what to suggest. QM 3.0 has several changes in it though which ensure it continues to work when jQuery is broken, so hopefully it's still somewhat usable.

**Comment by anugupta** [comment] 2018-05-22 12:35
I'm getting this on all Gravity Forms admin pages. 

![query-monitor 2018-05-22 13-33-39](https://user-images.githubusercontent.com/105964/40362555-bfdbed24-5dc4-11e8-8305-d6150b051d92.png)

The only error message in the console is:

```
A JavaScript problem on the page is preventing Query Monitor from working correctly. jQuery may have been blocked from loading.
(anonymous) @ admin.php?page=gf_settings:783
```
(the PHP file will change depending on which GF admin screen is being viewed)

**Comment by johnbillion** [comment] 2018-05-22 17:46
I'm gonna close this as a duplicate of #325 which I believe has the same root cause.

**Closed by johnbillion** 2018-05-22 17:46 UTC
Labels: awaiting feedback, jquery
