### ISSUE TITLE
Problem after deactivating / deleting Query Monitor in Wordpress

### ISSUE THREAD

**Issue by highlighter20** [johnbillion/query-monitor#464] opened 2019-08-29 11:55 UTC
Please help me. (I have also posted this on the wordpress.org site today). An error appears on the top of my wordpress website pages. I had the following detailed error message related to query-monitor plugin within my wordpress website: https://inspiredtohired.com. This happened after I moved to new host, and was cutting down on plugins due to speed issues and chose to temporarily delete Query Monitor. It reads as follows:-
Error: SyntaxError: Unexpected token / in JSON at position 0
Response: /var/sites/i/inspiredtohired.com/public_html/wp-content/
plugins/query-monitor/wp-content/
db.php{“status”:”1″,”count”.”1″,”total”:”46″,”activeJob”:”Yoast SEO”,””,”onlyActive”:””,”results”:”0″,”:97.82608695652
1735}

The page I need help with: https://inspiredtohired.com Thank you!

**Comment by highlighter20** [comment] 2019-08-29 12:10
![ErrorQuery-Monitor](https://user-images.githubusercontent.com/54670281/63939090-4d0dd700-ca5e-11e9-878c-dd7b29557fa2.png)

**Comment by highlighter20** [comment] 2019-08-29 12:14
This is still an open issue. Please ignore the 'closed' status. It is definitely new and open! Thanks.

**Comment by johnbillion** [comment] 2019-08-29 15:39
This is most likely caused by an error on your site in an Ajax response. With QM active, the error output gets suppressed and included in the headers.

You should be able to fix this by setting `WP_DEBUG_DISPLAY` to false in your wp-config.php file. Take a look in your browser's dev tools to inspect the Ajax response and look for any errors.

This isn't a QM issue, so I'm closing this off.

**Closed by johnbillion** 2019-08-29 15:39 UTC

**Comment by highlighter20** [comment] 2019-09-02 12:21
Thanks John... I'll check this out.
