### ISSUE TITLE
PHP Notice: Undefined index in Backtrace.php & php_errors.php

### ISSUE THREAD

**Issue by slaFFik** [johnbillion/query-monitor#494] opened 2020-02-05 20:13 UTC
I have a plugin that includes via composer the [Action Scheduler v3](https://github.com/woocommerce/action-scheduler/) library.
I tried to use that lib `as_enqueue_async_action()` function, but got the error:

<details>
<summary>PHP Fatal error:  Uncaught exception 'RuntimeException'</summary>

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Error saving action: ActionScheduler_Action::$args too long. To ensure the args column can be indexed, action args should not be more than 191 characters when encoded as JSON.' in \my_plugin_dir\vendor\woocommerce\action-scheduler\classes\data-stores\ActionScheduler_DBStore.php:61
Stack trace:
#0 \my_plugin_dir\vendor\woocommerce\action-scheduler\classes\ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action))
#1 \my_plugin_dir\vendor\woocommerce\action-scheduler\classes\ActionScheduler_ActionFactory.php(69): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))
#2 \my_plugin_dir\vendor\woocommerce\action-scheduler\functions.php(16): ActionScheduler_ActionFactory->async('my_plugin_dir_action in \query-monitor\collectors\php_errors.php on line 82
```

</details>

So the page of my plugin was white-screened with uncaught exception and fatal error (rightfully), but above those errors I also found this from the QM v3.5.2 plugin:

```
PHP Notice: Undefined index: file in \query-monitor\classes\Backtrace.php on line 194
PHP Notice: Undefined index: file in \query-monitor\classes\Backtrace.php on line 195
PHP Notice: Undefined index: line in \query-monitor\classes\Backtrace.php on line 196
PHP Notice: Undefined index: file in \query-monitor\collectors\php_errors.php on line 72
```

**Comment by johnbillion** [comment] 2020-02-05 22:30
Thanks for the report

**Comment by johnbillion** [comment] 2022-09-09 00:04
I've made many improvements to the backtrace collection since this report. I'll close this off but if you can still reproduce it do please let me know. Thanks.

**Closed by johnbillion** 2022-09-09 00:04 UTC
Labels: type:bug, collector:php_errors
