### ISSUE TITLE
Query monitor taskbar shows on plugins details pop-up

### ISSUE THREAD

**Issue by Dartui** [johnbillion/query-monitor#355] opened 2018-07-29 12:45 UTC
As shown on picture, on the bottom of plugin details pop-up is Query Monitor taskbar. What is more it covers Update button

![obraz](https://user-images.githubusercontent.com/2657856/43366379-676aa6fe-933d-11e8-8798-98929047bc5a.png)

**Comment by johnbillion** [comment] 2018-08-09 13:53
Thanks! I'll get this fixed.

Note that it's technically correct that QM shows up here (and in other places that might at first seem unexpected, such as the Updates screen) but it's not useful 99% of the time and I need to figure out a better way to expose QM data in modal windows etc when it is needed.

**Comment by R0dri** [comment] 2020-10-30 16:38
Maybe this is related. The task bar covers information rather than pushing content (I think it should work like the browser inspector that pushes all the content rather than coming on top of it.

A temporary workaround could be making background transparent:
![image](https://user-images.githubusercontent.com/14064394/97729162-c82aad00-1aa8-11eb-8180-83336e068254.png)
(here is to show evidence the problem. I can't scroll further, I have to close the window to see what's below. which can be annoying.

I believe tinkering with the css can be a solution, but I am no guru on the topic. Can you confirm this is related? or should I make another issue.

**Comment by johnbillion** [comment] 2020-11-02 12:00
@R0dri On the front end QM doesn't (well, _usually_ doesn't) cover up the content of your theme but unfortunately in the WordPress admin area the CSS doesn't allow QM to avoid this, and it does cover up content. Not much that can be done about that unfortunately.

**Comment by R0dri** [comment] 2020-11-05 15:34
Thanks @johnbillion; Do you think a js script could modify the admin css so it does not cover up content? its not a big deal either way, but I think will greatly improve usability, specially if you don't have a large screen (probably working on a laptop?)

**Comment by johnbillion** [comment] 2020-11-05 16:30
To be honest I'm not sure. I didn't look much into the cause.

The long term aim is to build an optional browser extension that displays QM's output just like your browser dev tools. No ETA yet.

**Comment by johnbillion** [comment] 2020-12-07 22:34
This was fixed in version 3.6 (009360e).

**Closed by johnbillion** 2020-12-07 22:34 UTC
Labels: dispatcher:html, type:enhancement
