### ISSUE TITLE
An error of type E_ERROR was caused in line 312 of the file /var/www/wordpress/wp-content/plugins/query-monitor/classes/Util.php.

### ISSUE THREAD

**Issue by KennethErvinYoung** [johnbillion/query-monitor#767] opened 2023-05-26 00:18 UTC
Howdy!

WordPress has a built-in feature that detects when a plugin or theme
causes a fatal error on your site, and notifies you with this
automated email.

In this case, WordPress caught an error with one of your plugins, Query Monitor.

Error Details
=============
An error of type E_ERROR was caused in line 312 of the file
/var/www/wordpress/wp-content/plugins/query-monitor/classes/Util.php.
Error message: Uncaught Error: Class "QM_Component" not found in
/var/www/wordpress/wp-content/plugins/query-monitor/classes/Util.php:312
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/query-monitor/classes/Backtrace.php(276):
QM_Util::get_file_component()
#1 /var/www/wordpress/wp-content/plugins/query-monitor/classes/Backtrace.php(210):
QM_Backtrace::get_frame_component()
#2 /var/www/wordpress/wp-content/plugins/query-monitor/collectors/php_errors.php(274):
QM_Backtrace->get_component()
#3 /var/www/wordpress/wp-content/plugins/query-monitor/vendor/composer/ClassLoader.php(582):
QM_Collector_PHP_Errors->error_handler()
#4 /var/www/wordpress/wp-content/plugins/query-monitor/vendor/composer/ClassLoader.php(582):
include('...')
#5 /var/www/wordpress/wp-content/plugins/query-monitor/vendor/composer/ClassLoader.php(433):
Composer\Autoload\{closure}()
#6 /var/www/wordpress/wp-content/plugins/query-monitor/classes/Util.php(312):
Composer\Autoload\ClassLoader->loadClass()
#7 /var/www/wordpress/wp-content/plugins/query-monitor/classes/Backtrace.php(276):
QM_Util::get_file_component()
#8 /var/www/wordpress/wp-content/plugins/query-monitor/classes/Backtrace.php(210):
QM_Backtrace::get_frame_component()
#9 /var/www/wordpress/wp-content/plugins/query-monitor/collectors/transients.php(91):
QM_Backtrace->get_component()
#10 /var/www/wordpress/wp-content/plugins/query-monitor/collectors/transients.php(59):
QM_Collector_Transients->setted_transient()
#11 /var/www/wordpress/wp-includes/class-wp-hook.php(308):
QM_Collector_Transients->action_setted_blog_transient()
#12 /var/www/wordpress/wp-includes/class-wp-hook.php(332):
WP_Hook->apply_filters()
#13 /var/www/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#14 /var/www/wordpress/wp-includes/option.php(1038): do_action()
#15 /var/www/wordpress/wp-includes/cron.php(892): set_transient()
#16 /var/www/wordpress/wp-includes/cron.php(1002): spawn_cron()
#17 /var/www/wordpress/wp-includes/class-wp-hook.php(308): _wp_cron()
#18 /var/www/wordpress/wp-includes/class-wp-hook.php(332):
WP_Hook->apply_filters()
#19 /var/www/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#20 /var/www/wordpress/wp-settings.php(645): do_action()
#21 /var/www/wordpress/wp-config.php(142): require_once('...')
#22 /var/www/wordpress/wp-load.php(50): require_once('...')
#23 /var/www/wordpress/wp-admin/admin-ajax.php(22): require_once('...')
#24 {main}
  thrown

**Comment by crstauf** [comment] 2023-07-04 09:30
@KennethErvinYoung Please provide more information:

1. WordPress version
1. Query Monitor version
1. PHP version
1. Where Query Monitor was downloaded/installed from

If your running a dev version (clone of GitHub repository, then you'll need to read and follow instructions in [the Contributing doc](https://github.com/johnbillion/query-monitor/blob/master/CONTRIBUTING.md#setting-up-locally).

**Comment by johnbillion** [comment] 2023-10-18 10:25
I'll close this off as this was likely caused by an incomplete plugin update that can be fixed by deleting and reinstalling the plugin. Please feel free to reopen if the issue is persistent.

**Closed by johnbillion** 2023-10-18 10:25 UTC
