### ISSUE TITLE
Output partially obscured by admin menu

### ISSUE THREAD

**Issue by lumpysimon** [johnbillion/query-monitor#92] opened 2015-01-24 00:53 UTC
When using on admin pages with the admin menu in its non-collapsed state, the lefthand side of QM's output is obscured by the admin menu.

Affects versions 2.6.8 and 2.6.9, WordPress 4.1

**Comment by johnbillion** [comment] 2015-01-24 00:58
Which browser / OS? This should have been fixed in 163783b202d9f8109208f69fe18447d5e3dadebf

**Comment by lumpysimon** [comment] 2015-01-24 01:03
Firefox and Chrome on Windows 7

**Comment by lumpysimon** [comment] 2015-01-24 01:05
Also IE9

**Comment by Daronspence** [comment] 2015-01-25 02:11
I'm also having this issue. Wordpress Multisite. Maybe it has something to do with the admin bar output in single vs multi install?

Chrome latest version OSX Yosemite

**Comment by Daronspence** [comment] 2015-01-25 02:13
![Screenshot ](https://cloud.githubusercontent.com/assets/4062087/5889932/6cea12de-a405-11e4-96a3-19dc3f2aef83.png)

**Comment by rpkoller** [comment] 2015-02-10 09:20
The issue is the `margin left` property in the `body:not(.iframe).wp-admin.auto-fold #qm selector`. The present state is: 

![bildschirmfoto 2015-02-10 um 10 11 14](https://cloud.githubusercontent.com/assets/1665422/6124430/ba0bbda0-b10d-11e4-85a9-4281d171b0c3.png)

if you deactivate the property in the dev tools the sidebar width is ok again. 

![bildschirmfoto 2015-02-10 um 10 11 06](https://cloud.githubusercontent.com/assets/1665422/6124441/ce308f86-b10d-11e4-8d8f-fce9aa5ff3cb.png)

But I was only able to test the issue in the admin interface. In the front end i am unable to, there I get no output at all ( reported in another issue already ). Best regards Ralf

**Comment by johnbillion** [comment] 2015-02-15 04:16
Fixed in 163783b. Needs a bit more tweaking for content inside iframes, but it fixes the immediate issue.

**Closed by johnbillion** 2015-02-15 04:16 UTC
Labels: bug, output:html
