### ISSUE TITLE
Some undefined index on error page

### ISSUE THREAD

**Issue by Mte90** [johnbillion/query-monitor#478] opened 2019-10-16 12:44 UTC
```
[16-Oct-2019 12:41:56 UTC] PHP Notice:  Undefined index: file in /srv/www/domain/public_html/wp-content/plugins/query-monitor/classes/Backtrace.php on line 194
[16-Oct-2019 12:41:56 UTC] PHP Notice:  Undefined index: file in /srv/www/domain/public_html/wp-content/plugins/query-monitor/classes/Backtrace.php on line 195
[16-Oct-2019 12:41:56 UTC] PHP Notice:  Undefined index: line in /srv/www/domain/public_html/wp-content/plugins/query-monitor/classes/Backtrace.php on line 196
[16-Oct-2019 12:41:56 UTC] PHP Notice:  Undefined index: file in /srv/www/domain/public_html/wp-content/plugins/query-monitor/collectors/php_errors.php on line 76
```

**Comment by johnbillion** [comment] 2019-10-16 14:00
Grazie Daniele, which URL are you seeing this on please?

**Comment by sawwd** [comment] 2019-11-29 15:05
@johnbillion also on:

[29-Nov-2019 14:18:23 UTC] PHP Notice:  Undefined index: found_formatted in /../query-monitor/output/html/languages.php on line 85

Triggered in: /wp-admin/admin.php?page=wc-admin or any WooCommerce page.

P.S. I have WooCommerce Admin plugin enabled.

Thanks

**Comment by johnbillion** [comment] 2019-11-30 16:11
@sawwd Did this error only appear once when you updated QM, or does it appear repeatedly? Do you have any add-on plugins for QM installed?

**Comment by johnbillion** [comment] 2019-11-30 16:26
@sawwd Ah wait, I've found the problem. I'll get it fixed.

**Comment by johnbillion** [comment] 2019-11-30 16:26
@Mte90 Were you able to get any more information about the error you were seeing?

**Comment by Mte90** [comment] 2019-12-02 12:09
I don't remember why is happened, but is something that I have already reported in the past https://github.com/johnbillion/query-monitor/issues/266

**Comment by johnbillion** [comment] 2019-12-02 14:28
Grazie.

Duplicate of #266.

**Closed by johnbillion** 2019-12-02 14:29 UTC
