### ISSUE TITLE
php errors captured in ajax response QM header

### ISSUE THREAD

**Issue by sushidub** [johnbillion/query-monitor#262] opened 2017-07-20 20:51 UTC
In chasing down a bug today I eventually found it hiding in one of QM's response headers. 

<img width="560" alt="2017-07-20_qm-ajax-php-error_captured" src="https://user-images.githubusercontent.com/482622/28438212-97b26428-6d5a-11e7-99ad-e4c11d146ee0.png">

Safe to assume that the normal method QM uses to Warn/Notice php issues, was not ever triggered since the particular issue was thrown during an ajax exchange between .js and php? If correct, then is it again safe to assume the **QM headers in the response object** are **currently** the only way QM is handling this kind of **error/issue context**?

Either way, I just wanted to confirm (avoid my own confusion). 
Thanks in advance for all your work so far.

**Comment by johnbillion** [comment] 2017-07-22 20:52
Yeah this is a sort of hidden feature of QM that I've never found time to improve. QM _should_ trigger an `AJAX: Warning` message in the admin toolbar when the error occurs to alert you to the fact that an error occurred. You can inspect the errors in the response headers but also in the browser developer console where QM will dump the info in a more readable format.

**Comment by johnbillion** [comment] 2017-07-22 20:53
Duplicate of #39.

**Closed by johnbillion** 2017-07-22 20:53 UTC
