### ISSUE TITLE
Error Private Methods

### ISSUE THREAD

**Issue by EMembrillas** [johnbillion/query-monitor#565] opened 2020-12-30 10:11 UTC
Warning: Private methods cannot be final as they are never overridden by other classes in wp-content/plugins/query-monitor/classes/Plugin.php on line 63

**Comment by johnbillion** [comment] 2020-12-30 10:34
Thanks for the report! This is a duplicate of #562. I'll release an update soon.

**Closed by johnbillion** 2020-12-30 10:34 UTC
