### ISSUE TITLE
HTTP requests for wp-cron

### ISSUE THREAD

**Issue by Mte90** [johnbillion/query-monitor#191] opened 2016-05-30 10:01 UTC
![](https://cloud.githubusercontent.com/assets/403283/15646464/0f579254-265e-11e6-8777-a8ec92cb405e.png)
As the screenshot I get often this alert locally but because I am locally I don't care about the cron work, maybe we can define a constant to disable that alert.

**Comment by johnbillion** [comment] 2016-05-30 11:14
I've noticed this too. Ideally I'd like to get to the bottom of the actual problem in core.

**Comment by johnbillion** [comment] 2017-11-01 14:39
Thanks for the suggestion Daniele but I'm going to close this for now as it's not something I have any plans to work on. The root cause should really be investigated and fixed.

**Closed by johnbillion** 2017-11-01 14:39 UTC
Labels: output:html

**Comment by Mte90** [comment] 2017-11-02 10:42
Implement a constant to disable core notification can be an idea to implement something quickly without so many difficulties.
