### ISSUE TITLE
Query Monitor Seems to Contribute to Three PHP Warnings in Some Cases

### ISSUE THREAD

**Issue by scofennell** [johnbillion/query-monitor#455] opened 2019-06-19 13:15 UTC
Hi, I realize this is an odd ticket and probably most people can't repro it.  _**I can only repro it on a WP Engine install.**_  See screenshot, which depicts:

- Updated Core
- Updated QM
- QM is the only plugin active
- Twentynineteen theme is active on the main site.

I would not impugn my beloved QM as the cause of this error per se, but I **can** see that no errors are occuring once I deactivate QM (I determine this by monitoring the error log file).

I even went so far as to remove the WP Engine MU plugins in my reduced test case.

I fully realize that it's highly unlikely that QM is truly doing anything wrong; I come to you with an empty up, looking for suggestions.

<img width="1680" alt="Screen Shot 2019-06-19 at 9 05 41 AM" src="https://user-images.githubusercontent.com/1585637/59768539-8a8e0100-9272-11e9-8058-f6eec8dabec3.png">

**Comment by crstauf** [comment] 2019-07-10 12:37
@scofennell Duplicate of #391.

**Comment by johnbillion** [comment] 2019-07-10 13:06
Thanks @crstauf , yeah this is a WP Engine specific issue. Details in the ticket above.

**Closed by johnbillion** 2019-07-10 13:06 UTC
