### ISSUE TITLE
implode on null

### ISSUE THREAD

**Issue by scibiszPiotr** [johnbillion/query-monitor#316] opened 2018-03-09 13:10 UTC
In https://github.com/johnbillion/query-monitor/blob/a171c1f503712f591ec0feb14c74b192756d807e/output/html/caps.php#L69
id bug. 
$row['parts'] can by null, on my WP i have many logs:
"implode(): Invalid arguments passed"
$row: {
args: [
upload_files, 
1
], 
result: true, 
trace: Object QM_Backtrace
}

**Comment by johnbillion** [comment] 2018-03-09 14:12
Thanks for the report. This is a duplicate of #286.

**Closed by johnbillion** 2018-03-09 14:12 UTC
