### ISSUE TITLE
E_NOTICE: Undefined index: file

### ISSUE THREAD

**Issue by DeanMarkTaylor** [johnbillion/query-monitor#152] opened 2015-11-11 23:42 UTC
Seeing E_NOTICE messages in logs.

Note I do have "wp-query-monitor-included-files" activated which may or may not be related.

This a multisite install.

```
URL: http://example.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
Referrer: http://example.com/wp-admin/plugins.php
Error(E_NOTICE): Undefined index: file
Source: /var/sites/e/example.com/public_html/wp-content/plugins/query-monitor/output/html/languages.php [56]

Trace:
#1 [internal call] - shutdown_action_hook()
#2 /var/sites/e/example.com/public_html/wp-includes/load.php:611 - do_action('shutdown')
#3 /var/sites/e/example.com/public_html/wp-includes/plugin.php:503 - call_user_func_array(Array, Array)
#4 [internal call] - QM_Dispatcher_Html->dispatch('')
#5 /var/sites/e/example.com/public_html/wp-content/plugins/query-monitor/dispatchers/Html.php:185 - QM_Output_Html_Languages->output()

POST:
array (
)

SESSION:


GET:
array (
  'activate-multi' => 'true',
  'plugin_status' => 'all',
  'paged' => '1',
  's' => '',
)
```

**Comment by johnbillion** [comment] 2015-11-12 00:26
Thanks. Dupe of #144.

**Closed by johnbillion** 2015-11-12 00:26 UTC
