### ISSUE TITLE
Warnings about undefined constants in query-monitor/wp-content/db.php

### ISSUE THREAD

**Issue by mundschenk-at** [johnbillion/query-monitor#460] opened 2019-07-21 08:03 UTC
I've noticed warnings about having various undefined DB-related constants in `query-monitor/wp-content/db.php` on PHP 7.3.7, like this:

```
Warning: Use of undefined constant DB_HOST - assumed 'DB_HOST' (this will throw an Error in a future version of PHP) in /wp-content/plugins/query-monitor/wp-content/db.php on line 139
```

Affected constants: `DB_NAME`, `DB_PASSWORD `, `DB_USER`.

This is a multisite installation an Query Monitor is network-activated.

**Comment by johnbillion** [comment] 2019-07-21 08:10
Thanks for the report.

Do you have some strange configuration on your Multisite? For example in sunrise.php.

I ask because your database constants should be defined (usually in wp-config.php) before db.php loads, and if that's not the case then your database configuration is somehow incorrect.

**Comment by mundschenk-at** [comment] 2019-07-21 08:18
I'm using a minimal `sunrise.php` (no domain mapping plugin):

```php
<?php
if ( !defined( 'SUNRISE_LOADED' ) )
        define( 'SUNRISE_LOADED', 1 );

if ( defined( 'COOKIE_DOMAIN' ) ) {
        die( 'The constant "COOKIE_DOMAIN" is defined (probably in wp-config.php). Please remove or comment out that define() line.' );
}

// This is the important part.
define( 'COOKIE_DOMAIN', $_SERVER[ 'HTTP_HOST' ] );
```

The database constants are defined in `wp-config.php`. I'm not sure what (periodically) triggers the warnings - normal requests do not appear to do it, but the warnings repeat daily.

**Comment by johnbillion** [comment] 2019-07-21 10:55
In that case you might want to install Xdebug which will give you a stack trace with each error.

I'll close this off as is unlikely to be an issue with QM, let me know if you determine otherwise!

**Comment by mundschenk-at** [comment] 2019-07-21 10:58
> In that case you might want to install Xdebug which will give you a stack trace with each error.
> 
> I'll close this off as is unlikely to be an issue with QM, let me know if you determine otherwise!

Well, we are talking about a production site.

**Comment by johnbillion** [comment] 2022-03-17 20:23
I finally managed to reproduce this thanks to PHP 8.1 which has promoted this warning to a fatal error. I'll get a fix into the next release.

**Closed** 2022-03-17 20:26 UTC
Labels: type:task
