### ISSUE TITLE
Parameter 1 to wp_default_styles() expected to be a reference, value given

### ISSUE THREAD

**Issue by henrywright** [johnbillion/query-monitor#391] opened 2019-02-01 12:29 UTC
Query Monitor is reporting a PHP warning which relates to a call to `wp_register_style()`. See the `enqueue()` method in the `Debug_Bar` class for where the function is called.

The rest of the stack trace can be seen in the image below.

![screenshot 2019-02-01 at 12 26 05](https://user-images.githubusercontent.com/1963288/52122998-b5a5ea00-261c-11e9-8970-f26de0be010f.png)

**Comment by johnbillion** [comment] 2019-02-01 14:10
Thanks for the report Henry.

* Are you using any Debug Bar add-ons?
* Does this happen with all other plugins deactivated and a default theme in use?
* Which version of WordPress are you using?

**Comment by henrywright** [comment] 2019-02-01 15:16
Hi John

- No
- I haven't tried
 - 5.0.3

I realise my second answer isn't helpful. I will try this when I get some time early next week.

Noteworthy is the PHP version. 7.2 is being used.

**Comment by johnbillion** [comment] 2019-02-01 16:10
Cheers, I'll see if I can find some time to take a look.

**Comment by crstauf** [comment] 2019-02-01 16:12
I've had this issue as well on PHP 7.2, but hadn't yet confirmed the cause.

@henrywright what host do you see this error on?

**Comment by johnbillion** [comment] 2019-02-01 16:14
I've been running 7.2 locally for ages now and haven't seen this myself. Might be caused by a PHP configuration difference.

**Comment by henrywright** [comment] 2019-02-05 10:54
Hi @crstauf 

The host is WP Engine.

**Comment by crstauf** [comment] 2019-02-05 14:08
@johnbillion @henrywright Thats where I've experienced the issue as well. I suspect then that's it's something with WP Engine's platform config.

**Comment by johnbillion** [comment] 2019-02-05 14:12
I do know that WPE do some weird things with the Heartbeat JS handling. There might be something on their platform that causes an invalid value to get passed through the dependency resolution system in WordPress, but I'm not sure where it could be if I'm honest.

@henrywright Do you know if WPE open sources their platform code?

**Comment by henrywright** [comment] 2019-02-05 14:50
@johnbillion I don't know if WPE have their platform or plugin code in the open but looking at the install they seem to have the following plugins active

- wpe-advanced-cache-options
- wpe-content-performance
- wpengine-geoip

The following mu-plugins are active

- wpengine-common

**Comment by crstauf** [comment] 2019-02-05 15:13
@johnbillion pretty sure WPE platform code is closed.

**Comment by henrywright** [comment] 2019-02-08 14:49
`wp_default_styles()` expects an object to be passed by reference. Is passing an object by reference necessary? I think not.

My thinking is in PHP > 5, an object variable is just an object identifier which allows object accessors to find the object in the object pool. Imagine the identifier looks something like this "obj # 8". In the case of `wp_default_styles( &$styles )`, we are merely passing the identifier "obj # 8" by reference. This isn't really useful.

If we pass the identifier by **copy**, the `$styles` object variable inside `wp_default_styles()` will hold a copy of the same "obj # 8" identifier allowing us to work with the same object in the object pool.

```
function wp_default_styles( $styles ) {
    // The $styles object can still be manipulated here
}
```

This is why I think passing an object by reference isn't really necessary. This could be a fix but we would need to consider backwards compat if the function signature was changed in WP.

**Comment by crstauf** [comment] 2019-03-09 21:27
Noting that WP Engine has confirmed as an issue with their platform, and is investigating:
https://wordpress.org/support/topic/warning-parameter-1-to-wp_default_scripts-expected-to-be-a-reference/#post-10922726

**Comment by johnbillion** [comment] 2019-04-14 11:56
Thanks for the follow up. Closing as this is an issue with WPE.

**Closed by johnbillion** 2019-04-14 11:56 UTC
Labels: awaiting verification, type:bug

**Comment by henrywright** [comment] 2019-04-17 08:54
FYI 

This post was written by a person at WP Engine https://nodeflame.com/fix-parameter-1-to-wp_default-errors/
