### ISSUE TITLE
Some errors in /output/html/caps.php

### ISSUE THREAD

**Issue by LDAV** [johnbillion/query-monitor#286] opened 2017-11-26 09:09 UTC
`PHP Notice:  Undefined index: parts in /wp-content/plugins/query-monitor/output/html/caps.php on line 69`
`PHP Warning:  implode(): Invalid arguments passed in /wp-content/plugins/query-monitor/output/html/caps.php on line 69`
`PHP Notice:  Undefined index: user in /wp-content/plugins/query-monitor/output/html/caps.php on line 70`
`PHP Notice:  Undefined index: name in /wp-content/plugins/query-monitor/output/html/caps.php on line 89`

hope it helps

**Comment by GaryJones** [comment] 2017-12-07 21:11
I can confirm these notices and warning.

**Comment by braders** [comment] 2018-01-03 17:17
I am also experiencing this problem. We have created custom roles & caps with https://en-gb.wordpress.org/plugins/user-role-editor, so I wonder if this could be related.

**Comment by GaryJones** [comment] 2018-01-03 17:53
One of the clients sites, where I possibly saw these notices and warnings, also uses User Role Editor. 🤔️

**Comment by slaFFik** [comment] 2018-01-10 13:25
I have the same issue.
Got 68 records in error log in the same second:

> PHP Warning: implode(): Invalid arguments passed in .../query-monitor/output/html/caps.php on line 69

**Comment by braders** [comment] 2018-01-10 13:46
In case it is of use to anyone, I worked around this issue by unhooking the `caps` outputter. This means that the caps section of Query Monitor is completely hidden, but it does mean that you can continue to use the rest of QM without filling your logs with rubbish.

```php
add_filter('qm/outputter/html', 'query_monitor_hide_caps', 1); // Very early before other output hooks run

public function query_monitor_hide_caps($outputters)
{
	remove_filter( 'qm/outputter/html', 'register_qm_output_html_caps', 105, 2 );
	return $outputters;
}
```

**Comment by johnbillion** [comment] 2018-01-10 18:25
I saw this myself recently, but currently nothing is appearing in my logs. Anybody got an idea of when these appear? Any particular screen or action that you take?

**Comment by slaFFik** [comment] 2018-01-10 19:37
In my case - ordinary page loads. But some content on that pages is accessible to certain roles only. We have created custom roles with custom capabilities, which are working fine for logged in users. And everything works fine for logged out users too, but when we do some sort of load-testing - those QM errors are started to appear.

**Comment by stevesearer** [comment] 2018-01-26 00:42
I have been noticing these errors recently as well. After disabling plugins to find conflicts, the errors to finally stop after disabling the plugin [WP Disable](https://wordpress.org/plugins/wp-disable/).

The errors seemed to be happening with regard to the usage of `current_user_can('administrator')` and `current_user_can('editor')` on line 81 of `wp-disable/lib/class-wpperformance-admin.php` and went away when I removed them.

**Comment by johnbillion** [comment] 2018-01-26 10:05
Thanks for the comments everyone. Pretty sure I've found the cause. I'll get it fixed in the next point release.

**Comment by johnbillion** [comment] 2018-06-26 21:05
Turns out this isn't fixed, but I've found the problem.

**Closed** 2018-07-17 17:10 UTC
Labels: output:html, priority:2, type:bug
