### ISSUE TITLE
Logs panel: broken link

### ISSUE THREAD

**Issue by slaFFik** [johnbillion/query-monitor#848] opened 2024-01-25 16:56 UTC
The Logs panel has a message with a link that leads here: https://querymonitor.com/docs/logging-variables/

This is a broken link that generates 404.

Instead, it should lead here: https://querymonitor.com/wordpress-debugging/profiling-and-logging/#logging

<img width="588" alt="image" src="https://github.com/johnbillion/query-monitor/assets/282234/e04a26d7-3c4f-4ff3-a327-1648c5f67f2d">

**Comment by slaFFik** [comment] 2024-01-25 16:59
Apparently, it's fixed in `develop` here: https://github.com/johnbillion/query-monitor/commit/296735ab9f2539683f64c99519f6722561a7bcd9

But is not released yet.

**Comment by crstauf** [comment] 2024-01-25 21:17
Duplicate of #842.

**Closed** 2024-01-25 21:56 UTC
