### ISSUE TITLE
Load Query Monitor HTML on-demand?

### ISSUE THREAD

**Issue by Luc45** [johnbillion/query-monitor#354] opened 2018-07-24 02:29 UTC
Hello,

I am developing a website and I really appreciate the timing that Query Monitor provides me. It's an outstanding plugin.

However, Query Monitor loads a massive amount of HTML that is hidden until you click Query Monitor's timings tab on wp-admin bar, and, 99% of the time, we don't click it, thus generating this heavy HTML load that we don't need.

I would like to hear your thoughts on loading this HTML on-demand when clicking the dropdown menu, via AJAX?

And again, thanks a lot for this great, free and open-source plugin.

**Comment by lkraav** [comment] 2018-07-24 11:35
This makes a lot of sense to me.

**Comment by johnbillion** [comment] 2018-07-24 12:12
This is something I started working on in #292,  but the amount of work involved is more than the time I have available to work on it at the moment.

**Comment by johnbillion** [comment] 2018-07-24 13:03
To add to this, your suggested idea of loading QM's HTML via Ajax is also an option, but something that's well down my list of priorities. I've been gradually working toward support for data persistence in QM, which is a prerequisite for several pieces of functionality including export, aggregation, external storage, etc. Once that's in place it'll potentially open up the possibility of lazy loading QM's output.

**Comment by johnbillion** [comment] 2018-07-24 13:04
The alternative is to make sure you click on QM on every single page load, then there's no wasted HTML :-)

**Comment by Luc45** [comment] 2018-08-04 13:58
Rsrs, that's cool! Well, perhaps I could come up with a PR? I'll see!

**Comment by crstauf** [comment] 2019-02-16 01:52
@Luc45 What do you think about a constant that prevents the QM window from being printed, but would keep the admin bar menu item? 

`define( 'QM_PRINT_WINDOW', false )` would prevent the printing of the window. Perhaps that'd be an acceptable solution until [the items John mentions](https://github.com/johnbillion/query-monitor/issues/354#issuecomment-407398773) are completed?

You could define `QM_PRINT_WINDOW` based on the presence of a `$_GET` key/value... it'd require a reload, but could suit your need?

**Comment by johnbillion** [comment] 2020-10-09 09:38
Closing this as a duplicate of #291 which is the central ticket for everything relating to moving to client-side rendering.

**Closed by johnbillion** 2020-10-09 09:38 UTC
Labels: type:feature request

**Comment by Luc45** [comment] 2020-10-09 10:57
> @Luc45 What do you think about a constant that prevents the QM window from being printed, but would keep the admin bar menu item?
> 
> `define( 'QM_PRINT_WINDOW', false )` would prevent the printing of the window. Perhaps that'd be an acceptable solution until [the items John mentions](https://github.com/johnbillion/query-monitor/issues/354#issuecomment-407398773) are completed?
> 
> You could define `QM_PRINT_WINDOW` based on the presence of a `$_GET` key/value... it'd require a reload, but could suit your need?

Somehow I've missed this, sorry. I'm 1 year late to reply.

Thanks, that seems to be a functional workaround.

I hope #483 goes well, that is looking great.

Best regards,
Lucas
