### ISSUE TITLE
Plugin Breaks Visual Composer Functionality

### ISSUE THREAD

**Issue by LPackman** [johnbillion/query-monitor#269] opened 2017-09-29 09:36 UTC
Hello, Im no techy but found this breaks VC in my Shopkeeper theme, once disabled VC works fine again.
I hope this may help someone.
Thanks

**Comment by johnbillion** [comment] 2017-09-29 09:47
Thanks for the report. Can you provide some screenshots of the problem please?

**Comment by LPackman** [comment] 2017-09-29 10:16
Yes sure.
Please see before and after screen shots.
Just to add, VC text editor also appeared as html not the noob friendly WYSIWYG version.
I also noticed my jetpack wasnt loading the stats widget properly on my dashboard the widget was just continuously showing the loading emblem only just realized this also now works as well
![front-end-html-only](https://user-images.githubusercontent.com/32387274/31011791-726a9fc0-a507-11e7-8a20-f25c5d54d7f9.JPG)
![jetpack-broken](https://user-images.githubusercontent.com/32387274/31011792-728b112e-a507-11e7-9e17-d529f0ed740a.JPG)
![jetpack-fixed](https://user-images.githubusercontent.com/32387274/31011790-726534d6-a507-11e7-89d9-4813668488b5.JPG)
![vc-fixed](https://user-images.githubusercontent.com/32387274/31011788-726317fa-a507-11e7-94fd-6b5443ecd515.JPG)
![visual-composer-missing](https://user-images.githubusercontent.com/32387274/31011789-72640ade-a507-11e7-814a-cebe8a76b2b1.JPG)




.
Kind regards,
Lee

**Comment by LPackman** [comment] 2017-09-29 10:20
Also whichever page was set as the SHOP page was not fully editable whilst set as the Shop page within Woocommerce product settings page.

I hope this helps :)

**Comment by johnbillion** [comment] 2017-11-01 16:37
I suspect the root cause of this is due to too much output in Ajax responses. Closing as effectively a duplicate of #275.

**Closed by johnbillion** 2017-11-01 16:37 UTC
Labels: awaiting feedback, priority:3
