### ISSUE TITLE
WP-CLI Activation Doesn't seem to attach the admin menu

### ISSUE THREAD

**Issue by jgraup** [johnbillion/query-monitor#169] opened 2016-03-01 07:47 UTC
I just recently started started using WP_CLI and when I try to activate this plugin the admin menu doesn't show up. I've managed to fix it with the code below. Is there a reason this isn't used or hasn't been tried before? I saw some other issue about the symlinks (#142), but testing locally in Vagrant is showing this working as expected for me.

[`/query-monitor.php`#L33 ](https://plugins.trac.wordpress.org/browser/query-monitor/trunk/query-monitor.php#L33)

```
if ( 'cli' === php_sapi_name() && ! defined( 'QM_TESTS' ) ) {
	# For the time being, let's not load QM when using the CLI because we've no persistent storage and no means of
	# outputting collected data on the CLI. This will hopefully change in a future version of QM.
	if( defined('WP_CLI') && WP_CLI ){
		// you shall pass ...
	} else {
		return;
	}
}
```

```
vagrant@username:/vagrant/site$ wp plugin activate query-monitor
Success: Plugin 'query-monitor' activated.
vagrant@username:/vagrant/site$ wp plugin deactivate query-monitor
Success: Plugin 'query-monitor' deactivated.  
```

**Comment by johnbillion** [comment] 2016-03-01 07:49
Thanks for the report. This is a dupe of #142. The required capability doesn't get set up when activating with WP-CLI.

**Closed by johnbillion** 2016-03-01 07:49 UTC
