### ISSUE TITLE
PHP Notice:  Undefined index

### ISSUE THREAD

**Issue by HRoger** [johnbillion/query-monitor#307] opened 2018-02-01 19:10 UTC
Hi there,

PHP 7.1.4 I always get this issues:

[01-Feb-2018 19:02:31 UTC] PHP Stack trace:
[01-Feb-2018 19:02:31 UTC] PHP   1. shutdown_action_hook() /app/public/wp-includes/load.php:0
[01-Feb-2018 19:02:31 UTC] PHP   2. do_action() /app/public/wp-includes/load.php:679
[01-Feb-2018 19:02:31 UTC] PHP   3. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453
[01-Feb-2018 19:02:31 UTC] PHP   4. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
[01-Feb-2018 19:02:31 UTC] PHP   5. QM_Dispatcher_Html->dispatch() /app/public/wp-includes/class-wp-hook.php:286
[01-Feb-2018 19:02:31 UTC] PHP   6. QM_Output_Html_Caps->output() /app/public/wp-content/plugins/query-monitor/dispatchers/Html.php:201
[01-Feb-2018 19:02:31 UTC] PHP   7. implode() /app/public/wp-content/plugins/query-monitor/output/html/caps.php:69
[01-Feb-2018 19:02:31 UTC] PHP Notice:  Undefined index: user in /app/public/wp-content/plugins/query-monitor/output/html/caps.php on line 70

[01-Feb-2018 19:02:31 UTC] PHP Stack trace:
[01-Feb-2018 19:02:31 UTC] PHP   1. shutdown_action_hook() /app/public/wp-includes/load.php:0
[01-Feb-2018 19:02:31 UTC] PHP   2. do_action() /app/public/wp-includes/load.php:679
[01-Feb-2018 19:02:31 UTC] PHP   3. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453
[01-Feb-2018 19:02:31 UTC] PHP   4. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
[01-Feb-2018 19:02:31 UTC] PHP   5. QM_Dispatcher_Html->dispatch() /app/public/wp-includes/class-wp-hook.php:286
[01-Feb-2018 19:02:31 UTC] PHP   6. QM_Output_Html_Caps->output() /app/public/wp-content/plugins/query-monitor/dispatchers/Html.php:201
[01-Feb-2018 19:02:31 UTC] PHP Notice:  Undefined index: name in /app/public/wp-content/plugins/query-monitor/output/html/caps.php on line 89

[01-Feb-2018 19:02:31 UTC] PHP Stack trace:
[01-Feb-2018 19:02:31 UTC] PHP   1. shutdown_action_hook() /app/public/wp-includes/load.php:0
[01-Feb-2018 19:02:31 UTC] PHP   2. do_action() /app/public/wp-includes/load.php:679
[01-Feb-2018 19:02:31 UTC] PHP   3. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453
[01-Feb-2018 19:02:31 UTC] PHP   4. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
[01-Feb-2018 19:02:31 UTC] PHP   5. QM_Dispatcher_Html->dispatch() /app/public/wp-includes/class-wp-hook.php:286
[01-Feb-2018 19:02:31 UTC] PHP   6. QM_Output_Html_Caps->output() /app/public/wp-content/plugins/query-monitor/dispatchers/Html.php:201
[01-Feb-2018 19:02:31 UTC] PHP Notice:  Undefined index: parts in /app/public/wp-content/plugins/query-monitor/output/html/caps.php on line 69

Thanks

**Comment by johnbillion** [comment] 2018-02-02 10:42
Duplicate of #286

**Closed by johnbillion** 2018-02-02 10:42 UTC
